version: "3"
services:
  watchy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./requirements:/app/watchy/requirements
      - ./watchy:/app/watchy/watchy
    env_file:
      - .env_test
