version: "3"
services:
  watchy:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./requirements:/app/watchy/requirements
      - ./watchy:/app/watchy/watchy
      - ./downloads:/app/watchy/downloads
    env_file:
      - .env_test
