version: "3"
services:
  series:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./serieswatcher:/app/serieswatcher
    env_file:
      - .env
