version: "3"
services:
  series:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./downloads:/app/watchy/downloads
      - ./requirements:/app/watchy/requirements
      - ./tv:/app/watchy/tv
      - ./movie:/app/watchy/movie
    env_file:
      - .env
